# Generated by Django 5.0.6 on 2024-07-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('established_year', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companycategory')),
            ],
        ),
    ]
