# Generated by Django 5.0.6 on 2024-07-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_add_initial_categories'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
